# Generated by Django 6.0.1 on 2026-01-15 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('source', models.CharField(default='MetOffice', max_length=100)),
                ('unit', models.CharField(default='°C', max_length=20)),
            ],
            options={
                'unique_together': {('parameter', 'region')},
            },
        ),
        migrations.CreateModel(
            name='SeasonalWeatherFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.CharField(max_length=10)),
                ('value', models.FloatField(null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.weathermetric')),
            ],
        ),
        migrations.CreateModel(
            name='AnnualWeatherFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('value', models.FloatField(null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.weathermetric')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyWeatherFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('value', models.FloatField(null=True)),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='climate.weathermetric')),
            ],
            options={
                'unique_together': {('metric', 'year', 'month')},
            },
        ),
    ]
